<?php

namespace AppBundle\Repository;

/**
 * BannerPrincipalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerPrincipalRepository extends \Doctrine\ORM\EntityRepository
{
}
