<?php

namespace AppBundle\Repository;

/**
 * ContatoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatoRepository extends \Doctrine\ORM\EntityRepository
{
}
