<?php

namespace AppBundle\Repository;

/**
 * ParceiroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParceiroRepository extends \Doctrine\ORM\EntityRepository
{
}
